# permissions for end users to edit jobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-editor-role
rules:
- apiGroups:
  - l6p.io
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - l6p.io
  resources:
  - jobs/status
  verbs:
  - get
